apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: github-sensor
  namespace: argo-events
  
spec:
  
  template:
  dependencies:
    - name: github-es
      eventSourceName: github-es
      eventName: example

  triggers:

    - template:
        serviceAccountName: operate-workflow-sa
        name: github-webhook-wf-trigger
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                name: special-trigger
              spec:
                serviceAccountName: operate-workflow-sa
                entrypoint: git-clone
                templates:
                  - name: git-clone
                    inputs:
                      artifacts:
                      - name: argo-source
                        path: /src
                        git:
                          repo: https://github.com/argoproj/argo-workflows.git
                          revision: "v2.1.1"
                    container:
                    image: golang:1.10
                    command: [sh, -c]
                    args: ["git status && ls && cat VERSION"]
                    workingDir: /src
          parameters:
            - src:
                dependencyName: github-es
                dataKey: body
              dest: spec.arguments.parameters.0.value
              


      