apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: github-ci-wf # name of this workflow

spec:
  entrypoint: git-clone
  templates:
    - name: git-clone
      inputs:
        artifacts:
          - name: django-todo
            path: django-todoapp-master/
            git:
              repo: https://github.com/harshagr64/django-todo-argo-ci-cd
      container:
      image: golang:1.10
      command: [sh, -c]
      args: ["git status && ls && cat VERSION"]
      workingDir: django-todoapp-master/

  