apiVersion: v1

kind: Secret
type: Opaque

metadata:
    name: {{ .Release.Name }}-db-secret

data:
  POSTGRES_DB: {{ .Values.dbConfig.db_name }}
  POSTGRES_PASSWORD: {{ .Values.dbConfig.db_user }}
  POSTGRES_USER: {{ .Values.dbConfig.db_pass }}

