apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
     app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          resources: {}
          image: harshagr63/task1_main:latest
          ports:
            - containerPort: 8000
          env:
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: postgresdb-configmap
                  key: db_name
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgresdb-configmap
                  key: db_port
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgresdb-configmap
                  key: db_host
          volumeMounts:
            - mountPath: /app/todoapp/staticfiles
              name: static-files
      volumes:
        - name: static-files
          emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000


  