FROM postgres:12

RUN apt update -y && apt install -y wget && apt install -y gnupg && wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | apt-key add -
RUN apt-get install apt-transport-https
RUN echo "deb https://artifacts.elastic.co/packages/8.x/apt stable main" | tee -a /etc/apt/sources.list.d/elastic-8.x.list
RUN apt-get update -y && apt-get install -y filebeat
RUN apt install -y systemctl && apt install -y nano